MODEL:
  REID_CKPT: weights/osnet_x0_25_msmt17.pt

DETECTION:
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5

TRACKER:
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100

DISTANCE_METRIC:
  MAX_DIST: 0.2